import json

# Compile all high-value industrial emission nodes and physical obstacle chimneys
industrial_nodes = [
    # --- TERMOELÉCTRICAS (AES ANDES / CAMPICHE / VENTANAS) ---
    {
        "id": "ind_termo_ventanas_1",
        "name": "Central Termoeléctrica Ventanas I (AES Andes)",
        "category": "emission_source",
        "type": "energy",
        "role": "Unidad de Generación a Carbón (Histórica/En Desmantelamiento) - Foco Emisor de SO2 y Cenizas",
        "icon": "🏭",
        "color": "#dc2626",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, MP10, MP2.5, Cenizas",
        "coords": [-71.483289, -32.751541, 15]
    },
    {
        "id": "ind_termo_ventanas_2",
        "name": "Central Termoeléctrica Ventanas II (AES Andes)",
        "category": "emission_source",
        "type": "energy",
        "role": "Generación Térmica a Carbón - Emisión de Gases de Combustión y Dispersión Atmosférica",
        "icon": "🏭",
        "color": "#dc2626",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, MP2.5, Metales Pesados",
        "coords": [-71.483305, -32.750955, 16]
    },
    {
        "id": "ind_termo_nueva_ventanas",
        "name": "Central Nueva Ventanas (AES Andes)",
        "category": "emission_source",
        "type": "energy",
        "role": "Unidad Térmica de Gran Escala - Monitoreo Crítico de Penacho Aéreo DAN 151",
        "icon": "🏭",
        "color": "#dc2626",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, MP10",
        "coords": [-71.483151, -32.749810, 16]
    },
    {
        "id": "ind_termo_campiche",
        "name": "Central Termoeléctrica Campiche (AES Andes)",
        "category": "emission_source",
        "type": "energy",
        "role": "Complejo Generador Térmico Campiche - Punto de Máxima Carga Emisora Costera",
        "icon": "🏭",
        "color": "#dc2626",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, MP2.5, CO2",
        "coords": [-71.483297, -32.748294, 17]
    },
    # --- CHIMENEAS CRÍTICAS (OBSTÁCULOS FÍSICOS Y FUENTES PUNTUALES) ---
    {
        "id": "ind_chimney_ventanas_1",
        "name": "Chimenea Complejo Ventanas #1 (Altura ~110m)",
        "category": "emission_source",
        "type": "chimney",
        "role": "Fuente Puntual de Alta Emisión y Obstáculo Vertical Severo para UAVs (DAN 151)",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, Pluma Térmica Ascendente",
        "coords": [-71.481487, -32.749839, 110]
    },
    {
        "id": "ind_chimney_ventanas_2",
        "name": "Chimenea Complejo Ventanas #2 (Altura ~115m)",
        "category": "emission_source",
        "type": "chimney",
        "role": "Punto de Intercepción de Pluma de Emisión Industrial (50-110m AGL)",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, Turbulencia Térmica",
        "coords": [-71.482509, -32.750788, 115]
    },
    {
        "id": "ind_chimney_ventanas_3",
        "name": "Chimenea Complejo Ventanas #3 (Altura ~120m)",
        "category": "emission_source",
        "type": "chimney",
        "role": "Fuente de Emisión y Límite Superior de Operación SORA",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, PM",
        "coords": [-71.482441, -32.751410, 120]
    },
    {
        "id": "ind_chimney_campiche",
        "name": "Chimenea Central Campiche (Altura ~140m)",
        "category": "emission_source",
        "type": "chimney",
        "role": "Superestructura Vertical y Emisión Convectiva Principal Zona Norte",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "SO2, NOx, MP2.5",
        "coords": [-71.481684, -32.748424, 140]
    },
    # --- FUNDICIÓN Y REFINERÍA CODELCO VENTANAS ---
    {
        "id": "ind_codelco_refineria",
        "name": "Refinería Electrolítica Codelco Ventanas",
        "category": "emission_source",
        "type": "metallurgy",
        "role": "Instalación Metalúrgica Activa (Electroobtención de Cobre y Subproductos)",
        "icon": "🏭",
        "color": "#ea580c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "Aerosoles Ácidos, Neblina Sulfúrica, Metales",
        "coords": [-71.479937, -32.759468, 22]
    },
    {
        "id": "ind_chimney_codelco",
        "name": "Chimenea Principal Ex-Fundición Codelco Ventanas (Altura ~152m)",
        "category": "emission_source",
        "type": "chimney",
        "role": "Obstáculo Aéreo Crítico de Gran Altura e Hito de Monitoreo de Gases Residuales",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "Gases de Proceso, Dispersión Histórica",
        "coords": [-71.480864, -32.762488, 152]
    },
    # --- TERMOELÉCTRICA QUINTERO ---
    {
        "id": "ind_termo_quintero",
        "name": "Central Termoeléctrica Quintero (Enel / Nehuenco)",
        "category": "emission_source",
        "type": "energy",
        "role": "Central Térmica a Ciclo Combinado (Gas/Diésel) - Zona Sur Bahía",
        "icon": "🏭",
        "color": "#dc2626",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "NOx, CO, CO2, Dispersión Aérea Sur",
        "coords": [-71.486192, -32.787826, 30]
    },
    {
        "id": "ind_chimney_quintero_1",
        "name": "Chimenea Central Quintero #1",
        "category": "emission_source",
        "type": "chimney",
        "role": "Descarga de Gases de Turbinas de Combustión Quintero Sur",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "NOx, Pluma Convectiva",
        "coords": [-71.485904, -32.787293, 75]
    },
    {
        "id": "ind_chimney_quintero_2",
        "name": "Chimenea Central Quintero #2",
        "category": "emission_source",
        "type": "chimney",
        "role": "Descarga de Gases de Turbinas Ciclo Abierto/Combinado",
        "icon": "💨",
        "color": "#b91c1c",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "NOx, Gases Calientes",
        "coords": [-71.486342, -32.787820, 75]
    },
    # --- TERMINALES QUÍMICOS Y COMBUSTIBLES ---
    {
        "id": "ind_oxiquim_terminal",
        "name": "Terminal Marítimo Quintero Oxiquim",
        "category": "emission_source",
        "type": "chemicals",
        "role": "Recepción, Almacenamiento y Despacho de Sustancias Químicas y Graneles Líquidos",
        "icon": "☣",
        "color": "#ea580c",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "Compuestos Orgánicos Volátiles (COVs), Solventes, Hidrocarburos",
        "coords": [-71.485765, -32.768722, 14]
    },
    {
        "id": "ind_gnl_quintero",
        "name": "Terminal de Regasificación GNL Quintero",
        "category": "emission_source",
        "type": "gas",
        "role": "Terminal de Descarga y Regasificación de Gas Natural Licuado (Tanques Criogénicos)",
        "icon": "⛽",
        "color": "#f97316",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "Metano (CH4), COVs de Venteo, Riesgo Criogénico",
        "coords": [-71.489506, -32.779035, 20]
    },
    {
        "id": "ind_gasmar_terminal",
        "name": "Planta Terminal Gasmar",
        "category": "emission_source",
        "type": "gas",
        "role": "Importación y Almacenamiento Refrigerado de Gas Licuado de Petróleo (GLP - Propano/Butano)",
        "icon": "⛽",
        "color": "#f97316",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "Propano, Butano, Emisiones Fugitivas de GLP",
        "coords": [-71.482469, -32.768660, 25]
    },
    {
        "id": "ind_enap_monoboya",
        "name": "Terminal Marítimo Monoboya ENAP Quintero",
        "category": "emission_source",
        "type": "oil",
        "role": "Recepción de Crudo y Combustibles por Monoboya Marina y Oleoductos",
        "icon": "🛢",
        "color": "#ea580c",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "Hidrocarburos Totales, Vapores de Crudo, H2S",
        "coords": [-71.486467, -32.776094, 18]
    },
    {
        "id": "ind_enap_estanques",
        "name": "Parque de Estanques Terminal ENAP Quintero",
        "category": "emission_source",
        "type": "oil_storage",
        "role": "Almacenamiento Estratégico de Petróleo Crudo, Diésel y Kerosén de Aviación",
        "icon": "🛢",
        "color": "#ea580c",
        "priority": 5,
        "city": "Quintero",
        "pollutants": "COVs, Vapores de Combustibles Líquidos",
        "coords": [-71.490998, -32.782002, 28]
    },
    {
        "id": "ind_copec_lubricantes",
        "name": "Planta de Lubricantes COPEC Quintero",
        "category": "emission_source",
        "type": "oil",
        "role": "Producción, Mezcla y Envasado de Lubricantes Industriales y Automotrices",
        "icon": "🛢",
        "color": "#f59e0b",
        "priority": 4,
        "city": "Quintero",
        "pollutants": "Aerosoles de Aceites, Hidrocarburos",
        "coords": [-71.498029, -32.779321, 24]
    },
    {
        "id": "ind_copec_terminal_importados",
        "name": "Planta Terminal de Productos Importados COPEC",
        "category": "emission_source",
        "type": "oil_storage",
        "role": "Almacenamiento y Despacho Masivo de Combustibles Líquidos",
        "icon": "🛢",
        "color": "#f59e0b",
        "priority": 4,
        "city": "Quintero",
        "pollutants": "Vapores de Gasolina y Diésel",
        "coords": [-71.495839, -32.778925, 22]
    },
    {
        "id": "ind_combustible_marino",
        "name": "Terminal de Combustible Marino Ventanas",
        "category": "emission_source",
        "type": "bunkering",
        "role": "Abastecimiento de Combustible (Bunkering) a Buques y Naves de Carga",
        "icon": "🚢",
        "color": "#ea580c",
        "priority": 4,
        "city": "Las Ventanas",
        "pollutants": "Heavy Fuel Oil, Diésel Marino",
        "coords": [-71.468947, -32.746708, 12]
    },
    # --- CEMENTERAS Y ÁRIDOS ---
    {
        "id": "ind_cemento_melon_ventanas",
        "name": "Planta Molienda de Cemento - Melón Ventanas",
        "category": "emission_source",
        "type": "cement",
        "role": "Molienda de Clinker, Puzolana y Despacho de Cemento - Emisión de Material Particulado",
        "icon": "🏭",
        "color": "#d97706",
        "priority": 5,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "MP10, MP2.5, Polvo Mineral de Sílice",
        "coords": [-71.475214, -32.754565, 28]
    },
    {
        "id": "ind_cemento_melon_puchuncavi",
        "name": "Planta Cemento Melón (Puchuncaví / Rungue)",
        "category": "emission_source",
        "type": "cement",
        "role": "Instalación Industrial y Extracción de Minerales / Áridos - Sector Interior Puchuncaví",
        "icon": "🏭",
        "color": "#d97706",
        "priority": 5,
        "city": "El Rungue",
        "pollutants": "MP10, Polvo en Suspensión de Canteras",
        "coords": [-71.405680, -32.705840, 85]
    },
    # --- SUBESTACIONES Y OTRAS INDUSTRIAS ---
    {
        "id": "ind_subestacion_ventanas",
        "name": "Subestación Eléctrica Ventanas (Transelec)",
        "category": "emission_source",
        "type": "substation",
        "role": "Nodo de Transmisión Eléctrica de Alta Tensión (Campos Electromagnéticos y Riesgo SORA)",
        "icon": "⚡",
        "color": "#eab308",
        "priority": 4,
        "city": "Cordón Industrial Ventanas",
        "pollutants": "Interferencia Electromagnética / Alta Tensión",
        "coords": [-71.481286, -32.749333, 20]
    },
    {
        "id": "ind_subestacion_quintero",
        "name": "Subestación Eléctrica Quintero",
        "category": "emission_source",
        "type": "substation",
        "role": "Subestación de Distribución Eléctrica Seccional Quintero",
        "icon": "⚡",
        "color": "#eab308",
        "priority": 4,
        "city": "Quintero",
        "pollutants": "Alta Tensión / Red de Transmisión",
        "coords": [-71.483856, -32.751758, 22]
    },
    {
        "id": "ind_desalinizadora_pacifico",
        "name": "Planta Desalinizadora Aguas Pacífico",
        "category": "emission_source",
        "type": "industrial",
        "role": "Infraestructura Hídrica Industrial y Emisario Submarino de Salmuera",
        "icon": "💧",
        "color": "#0284c7",
        "priority": 4,
        "city": "Quintero",
        "pollutants": "Salmuera Industrial, Consumo Energético",
        "coords": [-71.478991, -32.787750, 25]
    },
    {
        "id": "ind_pfv_loncura",
        "name": "Parque Solar Fotovoltaico Loncura (PMGD)",
        "category": "emission_source",
        "type": "solar",
        "role": "Generación Fotovoltaica y Resplandor / Reflejo Óptico",
        "icon": "☀️",
        "color": "#eab308",
        "priority": 3,
        "city": "Loncura",
        "pollutants": "Ninguno (Generación Renovable / Área de Exclusión)",
        "coords": [-71.496759, -32.788246, 32]
    }
]

print(f"Total industrial emission & infrastructure nodes prepared: {len(industrial_nodes)}")
with open(r'c:\Users\Benjamin\Desktop\ruteo_redes\scripts\compiled_industrial_nodes.json', 'w', encoding='utf-8') as f:
    json.dump(industrial_nodes, f, indent=2, ensure_ascii=False)
